<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);NU1903;CS1591</NoWarn> <!-- Suppress CS1591 due to missing XML documentation -->
    <Authors>Vladyslav Zaiets</Authors>
    <PackageProjectUrl>https://github.com/sarmkadan/binance-p2p-monitor</PackageProjectUrl>
  </PropertyGroup>
</Project>